# emacs-mode: -*- python-*-
RCK_BANK1 = ('Macro 1',
 'Macro 2',
 'Macro 3',
 'Macro 4',
 'Macro 5',
 'Macro 6',
 'Macro 7',
 'Macro 8')
RCK_BANKS = (RCK_BANK1)
RCK_BOBS = (RCK_BANK1)
RCK_BNK_NAMES = ('Macros')
IMP_BANK1 = ('1 Start',
 '1 Transpose',
 '1 Stretch Factor',
 '1 Saturator Drive',
 '1 Filter Freq',
 '1 Filter Res',
 '1 Pan',
 '1 Volume')
IMP_BANK2 = ('2 Start',
 '2 Transpose',
 '2 Stretch Factor',
 '2 Saturator Drive',
 '2 Filter Freq',
 '2 Filter Res',
 '2 Pan',
 '2 Volume')
IMP_BANK3 = ('3 Start',
 '3 Transpose',
 '3 Stretch Factor',
 '3 Saturator Drive',
 '3 Filter Freq',
 '3 Filter Res',
 '3 Pan',
 '3 Volume')
IMP_BANK4 = ('4 Start',
 '4 Transpose',
 '4 Stretch Factor',
 '4 Saturator Drive',
 '4 Filter Freq',
 '4 Filter Res',
 '4 Pan',
 '4 Volume')
IMP_BANK5 = ('5 Start',
 '5 Transpose',
 '5 Stretch Factor',
 '5 Saturator Drive',
 '5 Filter Freq',
 '5 Filter Res',
 '5 Pan',
 '5 Volume')
IMP_BANK6 = ('6 Start',
 '6 Transpose',
 '6 Stretch Factor',
 '6 Saturator Drive',
 '6 Filter Freq',
 '6 Filter Res',
 '6 Pan',
 '6 Volume')
IMP_BANK7 = ('7 Start',
 '7 Transpose',
 '7 Stretch Factor',
 '7 Saturator Drive',
 '7 Filter Freq',
 '7 Filter Res',
 '7 Pan',
 '7 Volume')
IMP_BANK8 = ('8 Start',
 '8 Transpose',
 '8 Stretch Factor',
 '8 Saturator Drive',
 '8 Filter Freq',
 '8 Filter Res',
 '8 Pan',
 '8 Volume')
IMP_BOB = ('Global Time',
 'Global Transpose',
 '1 Transpose',
 '2 Transpose',
 '3 Transpose',
 '4 Transpose',
 '5 Transpose',
 '6 Transpose')
IMP_BANKS = (IMP_BANK1,
 IMP_BANK2,
 IMP_BANK3,
 IMP_BANK4,
 IMP_BANK5,
 IMP_BANK6,
 IMP_BANK7,
 IMP_BANK8)
IMP_BOBS = (IMP_BOB)
IMP_BNK_NAMES = ('Pad 1',
 'Pad 2',
 'Pad 3',
 'Pad 4',
 'Pad 5',
 'Pad 6',
 'Pad 7',
 'Pad 8')
OPR_BANK1 = ('Ae Attack',
 'Ae Decay',
 'Ae Sustain',
 'Ae Release',
 'A Coarse',
 'A Fine',
 'A Lev < Vel',
 'A Level')
OPR_BANK2 = ('Be Attack',
 'Be Decay',
 'Be Sustain',
 'Be Release',
 'B Coarse',
 'B Fine',
 'B Lev < Vel',
 'B Level')
OPR_BANK3 = ('Ce Attack',
 'Ce Decay',
 'Ce Sustain',
 'Ce Release',
 'C Coarse',
 'C Fine',
 'C Lev < Vel',
 'C Level')
OPR_BANK4 = ('De Attack',
 'De Decay',
 'De Sustain',
 'De Release',
 'D Coarse',
 'D Fine',
 'D Lev < Vel',
 'D Level')
OPR_BANK5 = ('Le Attack',
 'Le Decay',
 'Le Sustain',
 'Le Release',
 'LFO Rate',
 'LFO Mod',
 'LFO Type',
 'LFO R < K')
OPR_BANK6 = ('Fe Attack',
 'Fe Decay',
 'Fe Sustain',
 'Fe Release',
 'Filter Freq',
 'Filter Res',
 'Fe R < Vel',
 'Fe Amount')
OPR_BANK7 = ('Pe Attack',
 'Pe Decay',
 'Pe Sustain',
 'Pe Release',
 'Pe Init',
 'Glide Time',
 'Pe Amount',
 'Spread')
OPR_BANK8 = ('Time < Key',
 'Panorama',
 'Pan < Key',
 'Pan < Rnd',
 'Algorithm',
 'Time',
 'Tone',
 'Volume')
OPR_BOB = ('A Coarse',
 'B Level',
 'B Coarse',
 'B Fine',
 'Filter Freq',
 'Filter Res',
 'Time',
 'Tone')
OPR_BANKS = (OPR_BANK1,
 OPR_BANK2,
 OPR_BANK3,
 OPR_BANK4,
 OPR_BANK5,
 OPR_BANK6,
 OPR_BANK7,
 OPR_BANK8)
OPR_BOBS = (OPR_BOB)
OPR_BNK_NAMES = ('Oscillator A',
 'Oscillator B',
 'Oscillator C',
 'Oscillator D',
 'LFO',
 'Filter',
 'Pitch Modulation',
 'Routing')
SIM_BANK1 = ('Ve Attack',
 'Ve Decay',
 'Ve Sustain',
 'Ve Release',
 'S Start',
 'S Loop Length',
 'S Length',
 'S Loop Fade')
SIM_BANK2 = ('Fe Attack',
 'Fe Decay',
 'Fe Sustain',
 'Fe Release',
 'Filter Freq',
 'Filter Res',
 'Filt < Vel',
 'Fe < Env')
SIM_BANK3 = ('L Attack',
 'L Rate',
 'L R < Key',
 'L Wave',
 'Vol < LFO',
 'Filt < LFO',
 'Pitch < LFO',
 'Pan < LFO')
SIM_BANK4 = ('Pe Attack',
 'Pe Decay',
 'Pe Sustain',
 'Pe Release',
 'Glide Time',
 'Spread',
 'Pan',
 'Volume')
SIM_BOB = ('S Start',
 'S Loop Length',
 'S Length',
 'Ve Attack',
 'Ve Decay',
 'Ve Release',
 'Filter Freq',
 'Filter Res')
SIM_BANKS = (SIM_BANK1,
 SIM_BANK2,
 SIM_BANK3,
 SIM_BANK4)
SIM_BOBS = (SIM_BOB)
SIM_BNK_NAMES = ('Amplitude',
 'Filter',
 'LFO',
 'Pitch Modifiers')
SAM_BANK1 = ('Volume',
 'Ve Attack',
 'Ve Decay',
 'Ve Sustain',
 'Ve Release',
 'Vol < Vel',
 'Ve R < Vel',
 'Time')
SAM_BANK2 = ('Filter Type',
 'Filter Morph',
 'Filter Freq',
 'Filter Res',
 'Filt < Vel',
 'Filt < Key',
 'Fe < Env',
 'Shaper Amt')
SAM_BANK3 = ('Fe Attack',
 'Fe Decay',
 'Fe Sustain',
 'Fe Release',
 'Fe End',
 'Fe Mode',
 'Fe Loop',
 'Fe Retrig')
SAM_BANK4 = ('L 1 Wave',
 'L 1 Sync',
 'L 1 Sync Rate',
 'L 1 Rate',
 'Vol < LFO',
 'Filt < LFO',
 'Pan < LFO',
 'Pitch < LFO')
SAM_BANK5 = ('L 2 Wave',
 'L 2 Sync',
 'L 2 Sync Rate',
 'L 2 Rate',
 'L 2 R < Key',
 'L 2 St Mode',
 'L 2 Spin',
 'L 2 Phase')
SAM_BANK6 = ('L 3 Wave',
 'L 3 Sync',
 'L 3 Sync Rate',
 'L 3 Rate',
 'L 3 R < Key',
 'L 3 St Mode',
 'L 3 Spin',
 'L 3 Phase')
SAM_BANK7 = ('O Mode',
 'O Volume',
 'O Coarse',
 'O Fine',
 'Oe Attack',
 'Oe Decay',
 'Oe Sustain',
 'Oe Release')
SAM_BANK8 = ('Transpose',
 'Spread',
 'Pe < Env',
 'Pe Attack',
 'Pe Peak',
 'Pe Decay',
 'Pe Sustain',
 'Pe Release')
SAM_BOB = ('Ve Attack',
 'Ve Decay',
 'Ve Release',
 'Filter Freq',
 'Filter Res',
 'Filter Morph',
 'O Volume',
 'O Coarse')
SAM_BANKS = (SAM_BANK1,
 SAM_BANK2,
 SAM_BANK3,
 SAM_BANK4,
 SAM_BANK5,
 SAM_BANK6,
 SAM_BANK7,
 SAM_BANK8)
SAM_BOBS = (SAM_BOB)
SAM_BNK_NAMES = ('Volume',
 'Filter',
 'Filter Envelope',
 'LFO 1',
 'LFO 2',
 'LFO 3',
 'Oscillator',
 'Pitch')
ALG_BANK1 = ('OSC1 Level',
 'OSC1 Octave',
 'OSC1 Semi',
 'OSC1 Shape',
 'OSC2 Level',
 'OSC2 Octave',
 'OSC2 Semi',
 'OSC2 Shape')
ALG_BANK2 = ('OSC1 Balance',
 'F1 Freq',
 'F1 Resonance',
 'F1 Type',
 'OSC2 Balance',
 'F2 Freq',
 'F2 Resonance',
 'F2 Type')
ALG_BANK3 = ('FEG1 Attack',
 'FEG1 Decay',
 'FEG1 Sustain',
 'FEG1 Rel',
 'FEG2 Attack',
 'FEG2 Decay',
 'FEG2 Sustain',
 'FEG2 Rel')
ALG_BANK4 = ('F1 On/Off',
 'F1 Freq < LFO',
 'F1 Freq < Env',
 'F1 Res < LFO',
 'F2 On/Off',
 'F2 Freq < LFO',
 'F2 Freq < Env',
 'F2 Res < LFO')
ALG_BANK5 = ('AEG1 Attack',
 'AEG1 Decay',
 'AEG1 Sustain',
 'AEG1 Rel',
 'AEG2 Attack',
 'AEG2 Decay',
 'AEG2 Sustain',
 'AEG2 Rel')
ALG_BANK6 = ('AMP1 Level',
 'AMP1 Pan',
 'LFO1 Shape',
 'LFO1 Speed',
 'AMP2 Level',
 'AMP2 Pan',
 'LFO2 Shape',
 'LFO2 Speed')
ALG_BANK7 = ('Volume',
 'Noise On/Off',
 'Noise Level',
 'Noise Color',
 'Unison On/Off',
 'Unison Detune',
 'Vib On/Off',
 'Vib Amount')
ALG_BOB = ('F1 Freq',
 'F1 Resonance',
 'OSC1 Octave',
 'Vib On/Off',
 'AEG1 Attack',
 'AEG1 Rel',
 'Unison On/Off',
 'Volume')
ALG_BANKS = (ALG_BANK1,
 ALG_BANK2,
 ALG_BANK3,
 ALG_BANK4,
 ALG_BANK5,
 ALG_BANK6,
 ALG_BANK7)
ALG_BOBS = (ALG_BOB)
ALG_BNK_NAMES = ('Oscillators',
 'Filters',
 'Filter Envelopes',
 'Filter Modulation',
 'Volume Envelopes',
 'Mix',
 'Output')
ELC_BANK1 = ('M Stiffness',
 'M Force',
 'Noise Pitch',
 'Noise Decay',
 'Noise Amount',
 'F Tine Color',
 'F Tine Decay',
 'F Tine Vol')
ELC_BANK2 = ('F Tone Decay',
 'F Tone Vol',
 'F Release',
 'Damp Tone',
 'Damp Balance',
 'Damp Amount',
 '',
 '')
ELC_BANK3 = ('P Symmetry',
 'P Distance',
 'P Amp In',
 'P Amp Out',
 'Pickup Model',
 '',
 '',
 '')
ELC_BANK4 = ('M Stiff < Vel',
 'M Stiff < Key',
 'M Force < Vel',
 'M Force < Key',
 'Noise < Key',
 'F Tine < Key',
 'P Amp < Key',
 '')
ELC_BANK5 = ('Volume',
 'Polyphony',
 'Semitone',
 'Detune',
 'KB Stretch',
 'PB Range',
 '',
 '')
ELC_BOB = ('M Stiffness',
 'M Force',
 'Noise Amount',
 'F Tine Vol',
 'F Tone Vol',
 'F Release',
 'Damp Amount',
 'Volume')
ELC_BANKS = (ELC_BANK1,
 ELC_BANK2,
 ELC_BANK3,
 ELC_BANK4,
 ELC_BANK5)
ELC_BOBS = (ELC_BOB)
ELC_BNK_NAMES = ('Mallet and Tine',
 'Tone and Damper',
 'Pickup',
 'Modulation',
 'Global')
TNS_BANK1 = ('Excitator Type',
 'String Decay',
 'Str Inharmon',
 'Str Damping',
 'Exc X',
 'Exc Stiffness',
 'Exc Velocity',
 'E Pos')
TNS_BANK2 = ('Damper On',
 'Damper Mass',
 'D Stiffness',
 'D Velocity',
 'Damp Pos',
 'D Damping',
 'D Pos < Vel',
 'D Pos Abs')
TNS_BANK3 = ('Term On/Off',
 'Term Force',
 'Term Fng Stiff',
 'Term Fret Stiff',
 'Pickup On/Off',
 'Pickup Pos',
 'T Force < Vel',
 'T Force < Key')
TNS_BANK4 = ('Body On/Off',
 'Body Type',
 'Body Size',
 'Body Decay',
 'Body Low-Cut',
 'Body High-Cut',
 'Body Mix',
 'Volume')
TNS_BANK5 = ('Vibrato On/Off',
 'Vib Delay',
 'Vib Fade-In',
 'Vib Speed',
 'Vib Amount',
 'Vib < ModWh',
 'Vib Error',
 'Volume')
TNS_BANK6 = ('Filter On/Off',
 'Filter Type',
 'Filter Freq',
 'Filter Reso',
 'Freq < Env',
 'Freq < LFO',
 'Reso < Env',
 'Reso < LFO')
TNS_BANK7 = ('FEG On/Off',
 'FEG Attack',
 'FEG Decay',
 'FEG Sustain',
 'FEG Release',
 'LFO On/Off',
 'LFO Shape',
 'LFO Speed')
TNS_BANK8 = ('Unison On/Off',
 'Uni Detune',
 'Porta On/Off',
 'Porta Time',
 'Polyphony',
 'Octave',
 'Semitone',
 'Volume')
TNS_BOB = ('Excitator Type',
 'E Pos',
 'String Decay',
 'Str Damping',
 'Vib Amount',
 'Filter Freq',
 'Filter Reso',
 'Volume')
TNS_BANKS = (TNS_BANK1,
 TNS_BANK2,
 TNS_BANK3,
 TNS_BANK4,
 TNS_BANK5,
 TNS_BANK6,
 TNS_BANK7,
 TNS_BANK8)
TNS_BOBS = (TNS_BOB)
TNS_BNK_NAMES = ('Excitator and String',
 'Damper',
 'Termination and Pickup',
 'Body',
 'Vibrato',
 'Filter',
 'Envelope and LFO',
 'Global')
ARP_BANK1 = ('Style',
 'Groove',
 'Offset',
 'Synced Rate',
 'Retrigger Mode',
 'Ret. Interval',
 'Repeats',
 'Gate')
ARP_BANK2 = ('Tranpose Mode',
 'Tranpose Key',
 'Transp. Steps',
 'Transp. Dist.',
 'Velocity Decay',
 'Velocity Target',
 'Velocity On',
 'Vel. Retrigger')
ARP_BOB = ('Synced Rate',
 'Free Rate',
 'Transp. Steps',
 'Transp. Dist.',
 'Gate',
 'Tranpose Key',
 'Velocity Decay',
 'Velocity Target')
ARP_BANKS = (ARP_BANK1,
 ARP_BANK2)
ARP_BOBS = (ARP_BOB)
ARP_BNK_NAMES = ('Style',
 'Pitch/Velocity')
CRD_BANK1 = ('Shift1',
 'Shift2',
 'Shift3',
 'Shift4',
 'Shift5',
 'Shift6',
 '',
 '')
CRD_BANK2 = ('Velocity1',
 'Velocity2',
 'Velocity3',
 'Velocity4',
 'Velocity5',
 'Velocity6',
 '',
 '')
CRD_BOB = ('Shift1',
 'Shift2',
 'Shift3',
 'Shift4',
 'Shift5',
 'Velocity5',
 'Shift6',
 'Velocity6')
CRD_BANKS = (CRD_BANK1,
 CRD_BANK2)
CRD_BOBS = (CRD_BOB)
CRD_BNK_NAMES = ('Shift',
 'Shift %')
NTL_BANK1 = ('Sync On',
 'Time Length',
 'Synced Length',
 'Gate',
 'Vel./Rel.Vel',
 'Decay Time',
 'Decay Key Scale',
 '')
NTL_BANKS = (NTL_BANK1)
NTL_BOBS = (NTL_BANK1)
PIT_BANK1 = ('Pitch',
 'Range',
 'Lowest',
 '',
 '',
 '',
 '',
 '')
PIT_BANKS = (PIT_BANK1)
PIT_BOBS = (PIT_BANK1)
RND_BANK1 = ('Chance',
 'Choices',
 'Scale',
 'Sign',
 '',
 '',
 '',
 '')
RND_BANKS = (RND_BANK1)
RND_BOBS = (RND_BANK1)
SCL_BANK1 = ('Base',
 'Transpose',
 'Range',
 'Lowest',
 '',
 '',
 '',
 '')
SCL_BANKS = (SCL_BANK1)
SCL_BOBS = (SCL_BANK1)
VEL_BANK1 = ('Drive',
 'Compand',
 'Random',
 'Mode',
 'Out Hi',
 'Out Low',
 'Range',
 'Lowest')
VEL_BANKS = (VEL_BANK1)
VEL_BOBS = (VEL_BANK1)
AFL_BANK1 = ('Frequency',
 'Resonance',
 'Env. Attack',
 'Env. Release',
 'Env. Modulation',
 'LFO Amount',
 'LFO Frequency',
 'LFO Phase')
AFL_BANKS = (AFL_BANK1)
AFL_BOBS = (AFL_BANK1)
APN_BANK1 = ('Amount',
 'Frequency',
 'Phase',
 'Shape',
 'Waveform',
 'Sync Rate',
 'Offset',
 'Width (Random)')
APN_BANKS = (APN_BANK1)
APN_BOBS = (APN_BANK1)
BRP_BANK1 = ('Interval',
 'Offset',
 'Grid',
 'Variation',
 'Mid Freq',
 'EQ Width',
 'Volume',
 'Decay')
BRP_BANK2 = ('Chance',
 'Gate',
 'Pitch',
 'Pitch Decay',
 'Mid Freq',
 'EQ Width',
 'Volume',
 'Decay')
BRP_BOB = ('Interval',
 'Offset',
 'Gate',
 'Chance',
 'Grid',
 'Variation',
 'Pitch',
 'Mid Freq')
BRP_BANKS = (BRP_BANK1,
 BRP_BANK2)
BRP_BOBS = (BRP_BOB)
BRP_BNK_NAMES = ('Repeat Rate',
 'Gate/Pitch')
CHR_BANK1 = ('Delay 1 Time',
 'Delay 2 Time',
 'LFO Amount',
 'Dry/Wet',
 'Delay 1 HiPass',
 'Delay 2 Mode',
 'LFO Rate',
 'Feedback')
CHR_BANKS = (CHR_BANK1)
CHR_BOBS = (CHR_BANK1)
CP3_BANK1 = ('Threshold',
 'Ratio',
 'Attack',
 'Release',
 'Knee',
 'EF Mode',
 'LookAhead',
 'Model')
CP3_BANK2 = ('Ext. In On',
 'Ext. In Gain',
 'Ext. In Mix',
 'Side Listen',
 'EQ On',
 'EQ Freq',
 'EQ Q',
 'EQ Mode')
CP3_BANK3 = ('EQ Gain',
 'Makeup Gain',
 'Output Gain',
 '',
 '',
 '',
 '',
 '')
CP3_BOB = ('Threshold',
 'Ratio',
 'Attack',
 'Release',
 'Ext. In Gain',
 'Ext. In Mix',
 'EQ Freq',
 'Output Gain')
CP3_BANKS = (CP3_BANK1,
 CP3_BANK2,
 CP3_BANK3)
CP3_BOBS = (CP3_BOB)
CP3_BNK_NAMES = ('Compression',
 'Side Chain',
 'Output')
DTB_BANK1 = ('Dry/Wet',
 'Output',
 'Drive',
 'Tone',
 'Bias',
 'Envelope',
 'Attack',
 'Release')
DTB_BANKS = (DTB_BANK1)
DTB_BOBS = (DTB_BANK1)
EQ8_BOB = ('1 Frequency A',
 '1 Gain A',
 '2 Frequency A',
 '2 Gain A',
 '3 Frequency A',
 '3 Gain A',
 '4 Frequency A',
 '4 Gain A')
EQ8_BANK1 = ('1 Filter On A',
 '2 Filter On A',
 '3 Filter On A',
 '4 Filter On A',
 '5 Filter On A',
 '6 Filter On A',
 '7 Filter On A',
 '8 Filter On A')
EQ8_BANK2 = ('1 Frequency A',
 '2 Frequency A',
 '3 Frequency A',
 '4 Frequency A',
 '5 Frequency A',
 '6 Frequency A',
 '7 Frequency A',
 '8 Frequency A')
EQ8_BANK3 = ('1 Gain A',
 '2 Gain A',
 '3 Gain A',
 '4 Gain A',
 '5 Gain A',
 '6 Gain A',
 '7 Gain A',
 '8 Gain A')
EQ8_BANK4 = ('1 Resonance A',
 '2 Resonance A',
 '3 Resonance A',
 '4 Resonance A',
 '5 Resonance A',
 '6 Resonance A',
 '7 Resonance A',
 '8 Resonance A')
EQ8_BANK5 = ('1 Filter Type A',
 '2 Filter Type A',
 '3 Filter Type A',
 '4 Filter Type A',
 '5 Filter Type A',
 '6 Filter Type A',
 '7 Filter Type A',
 '8 Filter Type A')
EQ8_BANK6 = ('Output Gain',
 'Scale',
 '',
 '',
 '',
 '',
 '',
 '')
EQ8_BANK7 = ('1 Gain A',
 '1 Frequency A',
 '1 Resonance A',
 '2 Gain A',
 '2 Frequency A',
 '2 Resonance A',
 '3 Gain A',
 '3 Frequency A')
EQ8_BANKS = (EQ8_BANK1,
 EQ8_BANK2,
 EQ8_BANK3,
 EQ8_BANK4,
 EQ8_BANK5,
 EQ8_BANK6,
 EQ8_BANK7)
EQ8_BOBS = (EQ8_BOB)
EQ8_BNK_NAMES = ('Band On/Off',
 'Frequency',
 'Gain',
 'Resonance',
 'Filter Type',
 'General',
 'EQs 1-3')
EQ3_BANK1 = ('GainLo',
 'GainMid',
 'GainHi',
 '',
 'FreqLo',
 'FreqHi',
 'Slope',
 '')
EQ3_BANKS = (EQ3_BANK1)
EQ3_BOBS = (EQ3_BANK1)
ERO_BANK1 = ('Frequency',
 'Width',
 'Amount',
 'Mode',
 '',
 '',
 '',
 '')
ERO_BANKS = (ERO_BANK1)
ERO_BOBS = (ERO_BANK1)
FLD_BANK1 = ('1 EQ Freq',
 '1 EQ Width',
 '1 Beat Delay',
 '1 Beat Swing',
 '1 Feedback',
 '1 Pan',
 '1 Volume',
 'Dry')
FLD_BANK2 = ('2 EQ Freq',
 '2 EQ Width',
 '2 Beat Delay',
 '2 Beat Swing',
 '2 Feedback',
 '2 Pan',
 '2 Volume',
 'Dry')
FLD_BANK3 = ('3 EQ Freq',
 '3 EQ Width',
 '3 Beat Delay',
 '3 Beat Swing',
 '3 Feedback',
 '3 Pan',
 '3 Volume',
 'Dry')
FLD_BOB = ('1 EQ Freq',
 '1 Beat Delay',
 '1 Feedback',
 '1 Volume',
 '3 EQ Freq',
 '3 Beat Delay',
 '3 Feedback',
 '3 Volume')
FLD_BANKS = (FLD_BANK1,
 FLD_BANK2,
 FLD_BANK3)
FLD_BOBS = (FLD_BOB)
FLD_BNK_NAMES = ('Input L Filter',
 'Input L+R Filter',
 'Input R Filter')
FLG_BANK1 = ('Hi Pass',
 'Dry/Wet',
 'Delay Time',
 'Feedback',
 'Env. Modulation',
 'Env. Attack',
 'Env. Release',
 '')
FLG_BANK2 = ('LFO Amount',
 'Frequency',
 'LFO Phase',
 'Sync',
 'LFO Offset',
 'Sync Rate',
 'LFO Width (Random)',
 'LFO Waveform')
FLG_BOB = ('Hi Pass',
 'Delay Time',
 'Feedback',
 'LFO Amount',
 'Frequency',
 'Sync Rate',
 'Env. Modulation',
 'Dry/Wet')
FLG_BANKS = (FLG_BANK1,
 FLG_BANK2)
FLG_BOBS = (FLG_BOB)
FLG_BNK_NAMES = ('Frequency Controls',
 'LFO / S&H')
GRD_BANK1 = ('Spray',
 'Frequency',
 'Pitch',
 'Random',
 'Feedback',
 'DryWet',
 'Beat Swing',
 'Time Delay')
GRD_BANKS = (GRD_BANK1)
GRD_BOBS = (GRD_BANK1)
PHS_BANK1 = ('Poles',
 'Color',
 'Dry/Wet',
 'Frequency',
 'Env. Modulation',
 'Env. Attack',
 'Env. Release',
 'Feedback')
PHS_BANK2 = ('LFO Amount',
 'LFO Frequency',
 'LFO Phase',
 'LFO Sync',
 'LFO Offset',
 'LFO Synced Rate',
 'LFO Spin',
 'LFO Waveform')
PHS_BOB = ('Poles',
 'Color',
 'Frequency',
 'Feedback',
 'LFO Amount',
 'LFO Frequency',
 'Env. Modulation',
 'Dry/Wet')
PHS_BANKS = (PHS_BANK1,
 PHS_BANK2)
PHS_BOBS = (PHS_BOB)
PHS_BNK_NAMES = ('Frequency Controls',
 'LFO / S&H')
RDX_BANK1 = ('Bit Depth',
 'Sample Mode',
 'Sample Hard',
 'Sample Soft',
 'Bit On',
 '',
 '',
 '')
RDX_BANKS = (RDX_BANK1)
RDX_BOBS = (RDX_BANK1)
SAT_BANK1 = ('Drive',
 'Base',
 'Frequency',
 'Width',
 'Depth',
 'Output',
 'Dry/Wet',
 'Type')
SAT_BANK2 = ('WS Drive',
 'WS Lin',
 'WS Curve',
 'WS Damp',
 'WS Depth',
 'WS Period',
 'Dry/Wet',
 '')
SAT_BOB = ('Drive',
 'Base',
 'Frequency',
 'Depth',
 'WS Curve',
 'WS Depth',
 'WS Period',
 'WS Damp')
SAT_BANKS = (SAT_BANK1,
 SAT_BANK2)
SAT_BOBS = (SAT_BOB)
SAT_BNK_NAMES = ('General Controls',
 'Waveshaper Controls')
RSN_BANK1 = ('Frequency',
 'Width',
 'Global Gain',
 'Dry/Wet',
 'Decay',
 'I Note',
 'Color',
 'I Gain')
RSN_BANK2 = ('II Gain',
 'III Gain',
 'IV Gain',
 'V Gain',
 'II Pitch',
 'III Pitch',
 'IV Pitch',
 'V Pitch')
RSN_BOB = ('Decay',
 'I Note',
 'II Pitch',
 'III Pitch',
 'IV Pitch',
 'V Pitch',
 'Global Gain',
 'Dry/Wet')
RSN_BANKS = (RSN_BANK1,
 RSN_BANK2)
RSN_BOBS = (RSN_BOB)
RSN_BNK_NAMES = ('General / Mode I',
 'Modes II-IV')
SMD_BANK1 = ('L Beat Delay',
 'L Beat Swing',
 'L Time Delay',
 'Dry/Wet',
 'R Beat Delay',
 'R Beat Swing',
 'R Time Delay',
 'Feedback')
SMD_BANKS = (SMD_BANK1)
SMD_BOBS = (SMD_BANK1)
UTL_BANK1 = ('StereoSeparation',
 'Panorama',
 'Mute',
 'BlockDc',
 'Signal Source',
 'Gain',
 'PhaseInvertL',
 'PhaseInvertR')
UTL_BANKS = (UTL_BANK1)
UTL_BOBS = (UTL_BANK1)
RVB_BANK1 = ('In Freqency',
 'In Width',
 'PreDelay',
 'ER Spin On',
 'ER Spin Rate',
 'ER Spin Amount',
 'ER Shape',
 'DecayTime')
RVB_BANK2 = ('HiShelf Freq',
 'LowShelf Freq',
 'Chorus Rate',
 'Density',
 'HiShelf Gain',
 'LowShelf Gain',
 'Chorus Amount',
 'Scale')
RVB_BANK3 = ('DecayTime',
 'Freeze On',
 'Room Size',
 'Stereo Image',
 'ER Level',
 'Diffuse Level',
 'Dry/Wet',
 'Quality')
RVB_BOB = ('DecayTime',
 'Room Size',
 'Chorus Amount',
 'In Frequency',
 'HiShelf Freq',
 'HiShelf Gain',
 'Stereo Image',
 'Dry/Wet')
RVB_BANKS = (RVB_BANK1,
 RVB_BANK2,
 RVB_BANK3)
RVB_BOBS = (RVB_BOB)
RVB_BNK_NAMES = ('Reflections',
 'Diffusion Network',
 'Global')
VDS_BANK1 = ('Tracing Freq.',
 'Tracing Width',
 'Tracing Drive',
 'Crackle Density',
 'Pinch Freq.',
 'Pinch Width',
 'Pinch Drive',
 'Crackle Volume')
VDS_BANKS = (VDS_BANK1)
VDS_BOBS = (VDS_BANK1)
GTE_BANK1 = ('Threshold',
 'Floor',
 '',
 '',
 'Attack',
 'Hold',
 'Release',
 '')
GTE_BANKS = (GTE_BANK1)
GTE_BOBS = (GTE_BANK1)
PPG_BANK1 = ('EQ Freq',
 'EQ Width',
 'Time Delay',
 'Beat Delay',
 'Beat Swing',
 'Delay Mode',
 'Feedback',
 'Dry/Wet')
PPG_BANKS = (PPG_BANK1)
PPG_BOBS = (PPG_BANK1)
DEVICE_DICT = {'AudioEffectGroupDevice': RCK_BANKS,
 'MidiEffectGroupDevice': RCK_BANKS,
 'InstrumentGroupDevice': RCK_BANKS,
 'DrumGroupDevice': RCK_BANKS,
 'InstrumentImpulse': IMP_BANKS,
 'Operator': OPR_BANKS,
 'UltraAnalog': ALG_BANKS,
 'OriginalSimpler': SIM_BANKS,
 'MultiSampler': SAM_BANKS,
 'MidiArpeggiator': ARP_BANKS,
 'LoungeLizard': ELC_BANKS,
 'StringStudio': TNS_BANKS,
 'MidiChord': CRD_BANKS,
 'MidiNoteLength': NTL_BANKS,
 'MidiPitcher': PIT_BANKS,
 'MidiRandom': RND_BANKS,
 'MidiScale': SCL_BANKS,
 'MidiVelocity': VEL_BANKS,
 'AutoFilter': AFL_BANKS,
 'AutoPan': APN_BANKS,
 'BeatRepeat': BRP_BANKS,
 'Chorus': CHR_BANKS,
 'Compressor2': CP3_BANKS,
 'Tube': DTB_BANKS,
 'Eq8': EQ8_BANKS,
 'FilterEQ3': EQ3_BANKS,
 'Erosion': ERO_BANKS,
 'FilterDelay': FLD_BANKS,
 'Flanger': FLG_BANKS,
 'GrainDelay': GRD_BANKS,
 'Phaser': PHS_BANKS,
 'Redux': RDX_BANKS,
 'Saturator': SAT_BANKS,
 'Resonator': RSN_BANKS,
 'CrossDelay': SMD_BANKS,
 'StereoGain': UTL_BANKS,
 'Tube': DTB_BANKS,
 'Reverb': RVB_BANKS,
 'Vinyl': VDS_BANKS,
 'Gate': GTE_BANKS,
 'PingPongDelay': PPG_BANKS}
DEVICE_BOB_DICT = {'AudioEffectGroupDevice': RCK_BOBS,
 'MidiEffectGroupDevice': RCK_BOBS,
 'InstrumentGroupDevice': RCK_BOBS,
 'DrumGroupDevice': RCK_BOBS,
 'InstrumentImpulse': IMP_BOBS,
 'Operator': OPR_BOBS,
 'UltraAnalog': ALG_BOBS,
 'OriginalSimpler': SIM_BOBS,
 'MultiSampler': SAM_BOBS,
 'MidiArpeggiator': ARP_BOBS,
 'LoungeLizard': ELC_BOBS,
 'StringStudio': TNS_BOBS,
 'MidiChord': CRD_BOBS,
 'MidiNoteLength': NTL_BOBS,
 'MidiPitcher': PIT_BOBS,
 'MidiRandom': RND_BOBS,
 'MidiScale': SCL_BOBS,
 'MidiVelocity': VEL_BOBS,
 'AutoFilter': AFL_BOBS,
 'AutoPan': APN_BOBS,
 'BeatRepeat': BRP_BOBS,
 'Chorus': CHR_BOBS,
 'Compressor2': CP3_BOBS,
 'Tube': DTB_BOBS,
 'Eq8': EQ8_BOBS,
 'FilterEQ3': EQ3_BOBS,
 'Erosion': ERO_BOBS,
 'FilterDelay': FLD_BOBS,
 'Flanger': FLG_BOBS,
 'GrainDelay': GRD_BOBS,
 'Phaser': PHS_BOBS,
 'Redux': RDX_BOBS,
 'Saturator': SAT_BOBS,
 'Resonator': RSN_BOBS,
 'CrossDelay': SMD_BOBS,
 'StereoGain': UTL_BOBS,
 'Tube': DTB_BOBS,
 'Reverb': RVB_BOBS,
 'Vinyl': VDS_BOBS,
 'Gate': GTE_BOBS,
 'PingPongDelay': PPG_BOBS}
BANK_NAME_DICT = {'AudioEffectGroupDevice': RCK_BNK_NAMES,
 'MidiEffectGroupDevice': RCK_BNK_NAMES,
 'InstrumentGroupDevice': RCK_BNK_NAMES,
 'DrumGroupDevice': RCK_BNK_NAMES,
 'InstrumentImpulse': IMP_BNK_NAMES,
 'Operator': OPR_BNK_NAMES,
 'UltraAnalog': ALG_BNK_NAMES,
 'OriginalSimpler': SIM_BNK_NAMES,
 'MultiSampler': SAM_BNK_NAMES,
 'MidiArpeggiator': ARP_BNK_NAMES,
 'LoungeLizard': ELC_BNK_NAMES,
 'StringStudio': TNS_BNK_NAMES,
 'MidiChord': CRD_BNK_NAMES,
 'BeatRepeat': BRP_BNK_NAMES,
 'Compressor2': CP3_BNK_NAMES,
 'Eq8': EQ8_BNK_NAMES,
 'FilterDelay': FLD_BNK_NAMES,
 'Flanger': FLG_BNK_NAMES,
 'Phaser': PHS_BNK_NAMES,
 'Saturator': SAT_BNK_NAMES,
 'Resonator': RSN_BNK_NAMES,
 'Reverb': RVB_BNK_NAMES}

def number_of_parameter_banks(device):
    """ Determine the amount of parameter banks the given device has """
    result = 0
    if (device != None):
        result = 1
        if (device.class_name in DEVICE_DICT.keys()):
            device_bank = DEVICE_DICT[device.class_name]
            result = len(device_bank)
        else:
            param_count = len(list(device.parameters))
            result = (param_count / 8)
            if (not ((param_count % 8) == 0)):
                result += 1
    return result



def get_parameter_by_name(device, name):
    """ Find the given device's parameter that belongs to the given name """
    result = None
    for i in device.parameters:
        if (i.original_name == name):
            result = i
            break

    return result



# local variables:
# tab-width: 4
